name: build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build (.NET Framework)
    runs-on: windows-latest

    env:
      CONFIGURATION: Release
      PROJECT_PATH: EN3Cracker/EN3Cracker.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore packages
        run: nuget restore $env:PROJECT_PATH -SolutionDirectory .

      - name: Build
        run: msbuild $env:PROJECT_PATH /p:Configuration=$env:CONFIGURATION /v:m

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: EN3Cracker_${{ env.CONFIGURATION }}
          path: |
            EN3Cracker/bin/${{ env.CONFIGURATION }}/

      - name: Archive Release
        if: startsWith(github.ref, 'refs/tags/v')
        shell: pwsh
        run: |
          Compress-Archive -Path "EN3Cracker/bin/${{ env.CONFIGURATION }}/*" -DestinationPath "EN3Cracker.zip"

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: EN3Cracker.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

